# import yaml

# modalidades=""
# with open('server_settings.yml', 'r') as file:
#     data = yaml.safe_load(file)
#     for rank in data['ranks']:
#         print(data['ranks'][rank]['name'])
#         print(data['ranks'][rank]['rewards'])
    # print(modalidades)

# texto = "todo minuscula"
# print(texto.capitalize())

# ----- Server info
# info_cmd:
#   name: "Celestial Network"
#   version: "1.20.*"
#   ip: "¡Muy pronto!"
#   port: "¡Muy Pronto!"
#   state: "En desarrollo"
#   games:
#   - "Survival (En desarrollo)"
#   - "BoxPvP (En desarrollo)"
#   store: "En desarrollo"

# ranks:
#   novato:
#     name: " Novato"
#     # emoji: "<:novato:1207888704992055356>"
#     rewards:
#       Kits:
#       - "**Armadura**"
#       - "Protección 2"
#       - "Irrompibilidad 2"
#       - "**Espada**"
#       - "Filo 2"
#       - "Irrompibilidad 2"
#       - "**Herramientas**"
#       - "Eficiencia 2"
#       - "Fortuna 1"
#       - "Irrompibilidad 2"
#       - "**Variados**"
#       - "x1 Totem"
#       - "x64 Chuleta asada"
#       - "Protección xX"
#       comandos:
#       - "**/**feed"
#       - "**/**near"
#       - "**/**craft" 
#   explorador:
#     name: " Explorador"
#     # emoji: "<:explorador:1207888880544649258>"
#     rewards:
#       Kits:
#       - "**Armadura**"
#       - "Protección 3"
#       - "Irrompibilidad 3"
#       - "**Espada**"
#       - "Aspecto de fuego 2"
#       - "Filo 4"
#       - "**Herramientas**"
#       - "Eficiencia 4"
#       - "Fortuna 2"
#       - "Irrompibilidad 3"
#       - "**Variados**"
#       - "Totem"
#       - "x64 Chuleta asada"
#       - "x16 Manzana de oro"
#       - "x3 Manzana de oro encantada"
#       - "Protección xX"
#       comandos:
#       - "**/**feed"
#       - "**/**near"
#       - "**/**craft"
#       - "**/**fix"
#   experto:
#     name: " Experto"
#     # emoji: "<:experto:1207888830225711126>"
#     rewards:
#       Kits:
#       - "**Armadura**"
#       - "Protección 4"
#       - "Irrompibilidad 3"
#       - "Reparación"
#       - "**Espada**"
#       - "Aspecto de fuego 2"
#       - "Filo 5"
#       - "Saqueo 3"
#       - "Reparación"
#       - "Irrompibilidad 3"
#       - "**Herramientas**"
#       - "Eficiencia 5"
#       - "Fortuna 3"
#       - "Irrompibilidad 3"
#       - "Reparación"
#       - "**Variados**"
#       - "x1 Totem"
#       - "x64 Chuleta asada"
#       - "x16 Manzana de oro"
#       - "x5 Manzana de oro encantada"
#       - "Protección xX"
#       comandos:
#       - "**/**feed"
#       - "**/**near"
#       - "**/**craft"
#       - "**/**fix"
#       - "**/**ec"
#   heroe:
#     name: " Héroe"
#     # emoji: "<:heroe:1207888998849187840>"
#     rewards:
#       Kits:
#       - "**Armadura**"
#       - "Protección 5"
#       - "Irrompibilidad 4"
#       - "Reparación"
#       - "**Espada**"
#       - "Aspecto de fuego 3"
#       - "Filo 6"
#       - "Saqueo 3"
#       - "Reparación"
#       - "Irrompibilidad 4"
#       - "**Herramientas**"
#       - "Eficiencia 5"
#       - "Fortuna 4"
#       - "Irrompibilidad 4"
#       - "Reparación"
#       - "**Variados**"
#       - "Pico Toque de seda"
#       - "x2 Totem"
#       - "x64 Chuleta asada"
#       - "x16 Manzana de oro"
#       - "x10 Manzana de oro encantada"
#       - "Protección xX"
#       comandos:
#       - "**/**feed"
#       - "**/**near"
#       - "**/**craft"
#       - "**/**fix"
#       - "**/**ec"
#   leyenda:
#     name: " Leyenda"
#     # emoji: "<:leyenda:1207889065672708156>"
#     rewards:
#       Kits:
#       - "**Armadura**"
#       - "Protección 6"
#       - "Irrompibilidad 5"
#       - "Reparación"
#       - "**Espada**"
#       - "Aspecto de fuego 4"
#       - "Filo 7"
#       - "Saqueo 5"
#       - "Reparación"
#       - "Irrompibilidad 5"
#       - "**Herramientas**"
#       - "Eficiencia 7"
#       - "Fortuna 5"
#       - "Irrompibilidad 5"
#       - "Reparación"
#       - "**Variados**"
#       - "Pico Toque de seda"
#       - "x2 Totem"
#       - "x64 Chuleta asada"
#       - "x32 Manzana de oro"
#       - "x15 Manzana de oro encantada"
#       - "Protección xX"
#       comandos:
#       - "**/**feed"
#       - "**/**near"
#       - "**/**craft"
#       - "**/**fix"
#       - "**/**ec"
#       - "**/**heal" 
#   dios:
#     name: " Dios"
#     # emoji: "<:dios:1207889121876643860>"
#     rewards:
#       Kits:
#       - "**Armadura**"
#       - "Protección 8"
#       - "Irrompibilidad 6"
#       - "Reparación"
#       - "**Espada**"
#       - "Aspecto de fuego 5"
#       - "Filo 8"
#       - "Saqueo 5"
#       - "Reparación"
#       - "Irrompibilidad 6"
#       - "**Herramientas**"
#       - "Eficiencia 8"
#       - "Fortuna 6"
#       - "Irrompibilidad 6"
#       - "Reparación"
#       - "**Variados**"
#       - "Pico Toque de seda"
#       - "x2 Totem"
#       - "x64 Chuleta asada"
#       - "x32 Manzana de oro"
#       - "x15 Manzana de oro encantada"
#       - "Protección xX"
#       comandos:
#       - "**/**feed"
#       - "**/**near"
#       - "**/**craft"
#       - "**/**fix"
#       - "**/**ec"
#       - "**/**heal"
#       - "**/**fly"
